### ISSUE TITLE
Directions 

### ISSUE THREAD

**Issue by DALDEI** [satr/intellij-idea-plugin-connector-for-aws-lambda#1]
I found your plugin, it looks great.
But I cannot figure out how to use.
aws cli is installed and configured (use it hours a day for years).
I have a project that builds lambda functions, I have the plugin installed and the tools are showing but no list of functions.  The docs say to "Configure the project for lambda" -- ok -- how ?
whats the magic trick to tell the plugin to look at my project ?

**Comment by satr** [comment]
Hi
The plugin for now use predefined region Regions.US_EAST_1 - please try to create a function in this region and see if it gets available in the function list. 
I planned to add a region selector.

**Comment by satr** [comment]
Hi
I added a list of regions to the plugin v1.1 (maybe couple day on moderation stage).
The issue can be also caused by a corporate proxy - it is not supported at this moment.

**Comment by satr** [comment]
As JAR is needed: "Configure JAR-artifact for the project". There is no need to "Configure the project for lambda", only following general SDK requirements. 
Example of the function class:
```
public class YourFuncClass implements RequestHandler<Object, Object> {
    @Override
    public Object handleRequest(Object input, Context context) {
        return input.toString();
    }
}
```
And I added libraries:
aws-lambda-java-core
aws-java-sdk-lambda
aws-java-sdk-core

**Comment by satr** [comment]
The plugin has been improved recently - more features and diagnostics added. Please try latest version - maybe it would help with unclear behaviour you found.
Latest [version is v1.3](https://github.com/satr/intellij-idea-plugin-connector-for-aws-lambda/releases/tag/v1.3)
Thank you.
