### ISSUE TITLE
Sort function list in dropdown alphabetically

### ISSUE THREAD

**Issue by DragoX** [satr/intellij-idea-plugin-connector-for-aws-lambda#10]
Would it be better to sort function names in dropdown selector alphabetically rather than showing them in the order returned by AWS?
From my experience, it is little easier to find the function you need in the sorted list if you have a long list of lambdas.

**Comment by satr** [comment]
Good idea. Fixed in the last commit.

**Comment by satr** [comment]
Implemented in the version 1.6
