### ISSUE TITLE
Only last 50 CloudWatch Logs log events fetched

### ISSUE THREAD

**Issue by igorakkerman** [satr/intellij-idea-plugin-connector-for-aws-lambda#12]
My CloudWatch Logs log group has 69 events. Only the _first_ 50 events are fetched. This causes the _latest_ events to be missing.

**Comment by satr** [comment]
By default the limit for returned items is 50. I'll fix this.

**Comment by satr** [comment]
Fixed in the release [1.7.RC1](https://github.com/satr/intellij-idea-plugin-connector-for-aws-lambda/releases/tag/v1.7.RC1)
