### ISSUE TITLE
(Question) Other artifact support

### ISSUE THREAD

**Issue by Swinkid** [satr/intellij-idea-plugin-connector-for-aws-lambda#15]
Hey,

If i were to contribute to support additional languages, such as Node.JS, where would you suggest i start to contribute?

**Comment by satr** [comment]
Hi
I you keep in mind IDEA, not WebStorm - my plan was to decouple Java-artefact specific component, extract general logic to superclasses. E.g. ArtifactEntity is specific output container, which can have a more general superclass, used in core logic (like method getLastSelectedJarArtifactName would be getLastSelectedOutputEntityName, etc)

**Comment by Swinkid** [comment]
Hey,

I am aware this is IDEA. The ultimate edition supports way more than just Java. Thanks for pointing that out, I'll try take a look.

**Comment by satr** [comment]
I fixed this morning the basic support for the NodeJS - it was not much changes.
Please check the [RC1.7.RC2](https://github.com/satr/intellij-idea-plugin-connector-for-aws-lambda/releases/tag/v1.7.RC2) and the [commit](https://github.com/satr/intellij-idea-plugin-connector-for-aws-lambda/commit/daf506666cc72451ffecabe8ea36f8e09b915f87)
It is quick fix, if you wish, you can make it more safe and stable. E.g. - it os pretty doubtful code in the ProjectModelImpl.java, method collectArchivesFromPlainArtifacts().
Thank you for your suggestion.
