### ISSUE TITLE
Connector for AWS Lambda Not showing

### ISSUE THREAD

**Issue by bmyrtil** [satr/intellij-idea-plugin-connector-for-aws-lambda#3]
Ive installed the plugin but i do not see the Connector for AWS Lambda in my tools window. Am I missing a step?

**Comment by satr** [comment]
After installation there should be an item in the list, invoking by the icon in the left bottom corner (Tools Window?) - I just reinstalled this and put to the screenshots. Could you try again?
![connector for aws lambda - install](https://user-images.githubusercontent.com/702860/35832359-55600b3c-0acd-11e8-8a64-3c13c6b8f76f.jpg)

**Comment by satr** [comment]
I found it may happend when a plugin was installed while multiple IDEA instances where running and they were not restarted properly. Please try to open only one IDEA instance and re-install the plugin.

**Comment by bmyrtil** [comment]
Thank you for the reply. This issue can be closed as the err was on my part. Turns out I was trying to install this in PyCharm and not IDEA

**Comment by satr** [comment]
Thank you for your report. Would it be useful to have such plugin in PyCharm, do you think?
