### ISSUE TITLE
Not working behind a proxy

### ISSUE THREAD

**Issue by pati19992** [satr/intellij-idea-plugin-connector-for-aws-lambda#5]
Hello,

I am working behind a proxy and get the error message:"ERROR: Unable to execute HTTP request: lambda. eu-west-1. amazonaws. com". 

I have set the proxy settings in IntelliJ and they work.

Using the AWS CLI via the command line with set proxy variables works fine.

Can someone help me?

Greetings

**Comment by satr** [comment]
Please try this [pre-release 1.4.RC1](https://github.com/satr/intellij-idea-plugin-connector-for-aws-lambda/releases/tag/v1.4.RC1) - it allows to sync plugin connection proxy with IDEA settings

**Comment by satr** [comment]
In the release 1.4 - added a sync of proxy settings with IDEA settings (manual update with a button).
Could you please verify if it works for you?
Thank you
