### ISSUE TITLE
No JAR-artifacts found

### ISSUE THREAD

**Issue by dementiev** [satr/intellij-idea-plugin-connector-for-aws-lambda#6]
I run mvn package with success result, jar was created. But after clicking of refresh button i don't see any jars available.

DEBUG: Refresh list of JAR-artifacts in the project
DEBUG: Refresh JAR-artifact list.
INFO: No JAR-artifacts found.

**Comment by satr** [comment]
I probably did not test the way you build the artefact. Could you try [this sample app](https://github.com/satr/sample-java-app-with-jar-artifact) (following [instruction in the wiki](https://github.com/satr/sample-java-app-with-jar-artifact/wiki)).
If it works - is it possible to get a sample app similar to one you faced issue with and an instruction how to reproduce it?

**Comment by ghost** [comment]
I have the same problem as @dementiev. It's easy to reproduce. Create a maven project with jar packaging and build the project. The plugin won't find the resulting jar.

**Comment by satr** [comment]
I see. Let me look at this.

**Comment by satr** [comment]
Could you check if the artifact appeared in the project out? If so - it is needed to hit a button "Refresh lits of Jar artifacts" to show it in the artifact list (step 6 in the image below). I have planned a task to-do - to update it automatically.

If the project and a Jar-artifact is done differently in your case - could you describe steps, so I can reproduce it?
Thank you

![jar-not-show-in-maven-project-01](https://user-images.githubusercontent.com/702860/37093630-51700d56-2210-11e8-9936-9df73a6a3379.jpg)
![jar-not-show-in-maven-project-02](https://user-images.githubusercontent.com/702860/37093636-53aed2dc-2210-11e8-9671-f71912257a6a.jpg)
![jar-not-show-in-maven-project-03](https://user-images.githubusercontent.com/702860/37093638-55045a3a-2210-11e8-8ce4-394eac12132a.jpg)
![jar-not-show-in-maven-project-04](https://user-images.githubusercontent.com/702860/37093639-56747ae4-2210-11e8-9b9f-20801c1dab74.jpg)

**Comment by ghost** [comment]
The default output dir for maven is target.

Example:

mtest01/target/myjar-1.0-SNAPSHOT.jar

**Comment by satr** [comment]
Artifact list is automatically refreshed after a project or artifact build - implemented in [Pre-release 1.5.RC3](https://github.com/satr/intellij-idea-plugin-connector-for-aws-lambda/releases/tag/v1.5.RC3)

**Comment by satr** [comment]
I think I managed to reproduce the issue properly now (image below). Seems I need to find the way to add this approach in addition to the implemented (and described above).
Thank you for your report.
![maven-jar-artifact-not-found-in-its-target](https://user-images.githubusercontent.com/702860/37124078-1b458362-2267-11e8-8c07-1c82a1d33de9.jpg)

**Comment by satr** [comment]
Maven project artifacts supported - build an artifact with a Maven project and hit the button "Refresh list of JAR artifacts".
Please try this in the pre-release [v1.5.RC4](https://github.com/satr/intellij-idea-plugin-connector-for-aws-lambda/releases/tag/v1.5.RC4)

![jar-shown-in-maven-project-01](https://user-images.githubusercontent.com/702860/37210924-9f6cc3f0-23aa-11e8-985f-d0eb5a5eb5ca.jpg)
